### ISSUE TITLE
Need to add couple of new buttons on top nav

### ISSUE THREAD

**Issue by haseeb1431** [haseeb1431/ProjectR#3]
New button > product, addnew 
; sales --> orders

**Comment by raheel06** [comment]
Product, Add New Product and Orders button somewhere on Dashboard and top menu on public store.

**Comment by haseeb1431** [comment]
Uploaded on stage, let me know once it's ok and need to upload on live

**Comment by raheel06** [comment]
1- These buttons should be both on Dashboard and top menu on public store.
2- These are kind of Quick Links. They can be showing above the categories list in side bar with heading as Quick Links
3- Button Names should be as below
My Products
My Orders
Add New Product

**Comment by raheel06** [comment]
Not Done.
