### ISSUE TITLE
Update Fevicon to new logo

### ISSUE THREAD

**Issue by raheel06** [haseeb1431/ProjectR#7]
Need to Update Fevicon as our logo has been upgraded.

**Comment by haseeb1431** [comment]
http://foriorder.pk/favicon.ico

Please let me know If I need to update this?

**Comment by raheel06** [comment]
yes, kindly do this on live.

**Comment by raheel06** [comment]
yah fix nhi kia ?

**Comment by raheel06** [comment]
@haseeb1431 yah fix nhi kia?
