### ISSUE TITLE
Facebook login is not working

### ISSUE THREAD

**Issue by raheel06** [haseeb1431/ProjectR#8]
Facebook login is not working as we have discussed on call.
Please look into this issue on priority.

**Comment by haseeb1431** [comment]
https://github.com/nopSolutions/nopCommerce/issues/2294

http://stackoverflow.com/questions/43094777/facebookapplication-verifyauthentication-httpcontext-generatelocalcallbackuri/43303067#43303067


http://www.nopcommerce.com/boards/t/46804/facebook-login-unknown-error.aspx?p=3
